// react-app/src/Navigation/Navigation.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const Navigation = () => (
  <nav>
    <ul>
      <li>
        <Link to="/">Home</Link>
      </li>
      <li>
        <Link to="/form-with-states">form with states</Link>
      </li>
      <li>
        <Link to="/form-with-references">form with references</Link>
      </li>
      <li>
        <Link to="/server-table">server table</Link>
      </li>
      <li>
        <Link to="/big-table">server table</Link>
      </li>
    </ul>
  </nav>
);

export default Navigation;

// vue-app/src/views/Navigation.vue
<template>
    <nav>
        <ul>
            <li>
                <router-link to="/">Home</router-link>
            </li>
            <li>
                <router-link to="/form-with-states">form with states</router-link>
            </li>
            <li>
                <router-link to="/form-with-references">form with references</router-link>
            </li>
            <li>
                <router-link to="/server-table">server table</router-link>
            </li>
            <li>
                <router-link to="/big-table">big table</router-link>
            </li>
        </ul>
    </nav>
</template>

<script>
  export default {
    name: 'Navigation',
  }
</script>
