// react-app/src/Navigation/Navigation.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const Navigation = () => (
  <nav>
    <ul>
      <li>
        <Link to="/">Home</Link>
      </li>
      <li>
        <Link to="/form-with-states">form with states</Link>
      </li>
      <li>
        <Link to="/form-with-references">form with references</Link>
      </li>
      <li>
        <Link to="/server-table">server table</Link>
      </li>
      <li>
        <Link to="/big-table">server table</Link>
      </li>
    </ul>
  </nav>
);

export default Navigation;

// angular-app/src/app/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.scss'],
})
export default class NavigationComponent implements OnInit {
  constructor() {
  }

  ngOnInit() {
  }
}

<nav>
  <ul>
    <li>
      <a routerLink="/" routerLinkActive="active">Home</a>
    </li>
    <li>
      <a routerLink="/form-with-binding" routerLinkActive="active">form with states</a>
    </li>
    <li>
      <a routerLink="/form-with-references" routerLinkActive="active">form with references</a>
    </li>
    <li>
      <a routerLink="/server-table" routerLinkActive="active">server table</a>
    </li>
    <li>
      <a routerLink="/big-table" routerLinkActive="active">server table</a>
    </li>
  </ul>
</nav>
