// vue-app/src/components/Table/Table.vue
<template>
    <div v-if="tableData" class="table-wrapper">
        <button
            v-for="button in buttons"
            :key="button.key"
            v-on:click="button.event()"
        >
            {{ button.text }}
        </button>
        <table v-if="isVisible">
            <tbody>
                <tr v-for="(row, rowIndex) in tableData" :key="`${rowIndex}row`">
                    <td v-for="(cell, cellIndex) in row" :key="`${cellIndex}cell`">
                        <div v-if="cell === true || cell === false">
                            <input type="checkbox" v-model="tableData[rowIndex][cellIndex]" />
                        </div>
                        <div v-else-if="typeof cell === 'string' && cell.includes('.png')">
                            <img :src="cell" alt="js logo">
                        </div>
                        <div v-else="!(isString(cell) && cell.includes('.png')) && !(cell === true || cell === false)">
                            {{ cell }}
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<style lang="scss">
    .table-wrapper {
        max-height: 500px;
        overflow: auto;
    }

    table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
        table-layout: fixed;
    }

    td {
        border: 1px solid #ddd;
        padding: 8px;

        &:last-child {
            padding: 0;
        }
    }

    tr {
        &:nth-child(even){
            background-color: #f2f2f2;
        }

        &:hover {
            background-color: #dddddd;
        }
    }

    img {
        height: 32px;
        width: 32px;
    }
</style>

<script>
import TableService from '../../services/TableService';
import ButtonModel from './ButtonModel';

export default {
  name: 'Table',
  props: ['bigTable'],
  data: function() {
    return {
      tableData: [],
      isVisible: true,
      buttons: [],
    };
  },
  mounted: async function() {
    if (this.bigTable) {
      const tableData = [];
      for (let i = 0; i < 300; i++) { // 30000 is fine
        if (i === 0) {
          tableData.push([
            'This is first item',
            false,
            1,
            'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
          ]);
        } else {
          tableData.push([
            'title',
            false,
            54,
            'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
          ]);
        }
      }
      this.tableData = tableData;
    } else {
      const response = await TableService.fetchTableData();
      this.tableData = response.data.tableData;
    }
    this.buttons = [
      new ButtonModel('moveRow', this.moveTableElement, 'Move row'),
      new ButtonModel('showHideTableButton', this.toggleTable, `${this.isVisible ? 'Hide' : 'Show'} table`),
      new ButtonModel('changeTextsButton', this.changeAllTexts, 'Change all texts'),
      new ButtonModel('changePartiallyTextsButton', this.changeTexts, 'Change partially text'),
      new ButtonModel('removeRow', this.removeRow, 'Remove row'),
      new ButtonModel('addRow', this.addRow, 'Add row'),
    ];
  },
  methods: {
    toggleTable: function () {
      this.isVisible = !this.isVisible;
    },
    moveTableElement: function () {
      const { tableData } = this;
      const firstRow = tableData.shift();
      tableData.splice(1, 0, firstRow);
      this.tableData = tableData;
    },
    changeTexts: function () {
      const { tableData } = this;
      for (let i = 0; i < tableData.length - 1; i += 10) {
        tableData[i][0] = String(Math.random());
      }
      this.tableData = tableData;
      this.buttons[2].key = `${this.buttons[2].key}o`;
    },
    changeAllTexts: function () {
      const { tableData } = this;
      tableData.forEach(row => {
        row[0] = String(Math.random());
      });
      this.tableData = tableData;
      this.buttons[3].key = `${this.buttons[3].key}p`;
    },
    removeRow: function () {
      const { tableData } = this;
      tableData.shift();
      this.tableData = tableData;
    },
    addRow: function () {
      const { tableData } = this;
      tableData.unshift([
        'Element added',
        false,
        60,
        'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
      ]);
      this.tableData = tableData;
    },
  },
}
</script>

// react-app/src/Table/Table.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import ButtonModel from "./ButtonModel";
import './Table.css';

class Table extends Component {
  state = {
    isVisible: true,
    tableData: [[]],
  };

  componentDidMount() {
    if (this.props.isBigTable) {
      const tableData = [];
      for (let i = 0; i < 300; i++) { // 30000 is fine
        if (i === 0) {
          tableData.push([
            'This is first item',
            false,
            1,
            'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
          ]);
        } else {
          tableData.push([
            'title',
            false,
            54,
            'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
          ]);
        }
      }
      this.setState({
        tableData,
      });
    } else {
      fetch('http://localhost:3001/table')
        .then(data => data.json())
        .then(({ tableData }) => {
          this.setState({
            tableData,
          });
        });
    }
  }

  selectRow = (rowIndex, cellIndex) => () => {
    const { tableData } = this.state;
    tableData[rowIndex][cellIndex] = !tableData[rowIndex][cellIndex];
    this.setState({
      tableData,
    });
  }

  getCells(cells, rowIndex) {
    return cells.map((cell, index) => {
      if (typeof cell === 'boolean') {
        return <td key={`${index}cell`}>
          <input type="checkbox" onChange={this.selectRow(rowIndex, index)} checked={cell} />
        </td>;
      } else if (typeof cell === 'string' && cell.includes('.png')) {
        return <td key={`${index}cell`}><img src={cell} alt="js logo" /></td>;
      }
      return <td key={`${index}cell`}>{cell}</td>;
    });
  }

  getRows(rows) {
    return rows.map((row, index) =>
      <tr key={`${index}row`}>
        {this.getCells(row, index)}
      </tr>
    );
  }

  moveTableElement = () => {
    const { tableData } = this.state;
    const firstRow = tableData.shift();
    tableData.splice(1, 0, firstRow);
    this.setState({
      tableData,
    });
  }

  changeTexts = (changeAll = false) => () => {
    const { tableData } = this.state;
    if (changeAll) {
      tableData.forEach(row => {
        row[0] = String(Math.random());
      });
    } else {
      for (let i = 0; i < tableData.length - 1; i += 10) {
        tableData[i][0] = String(Math.random());
      }
    }

    this.setState({
      tableData,
    });
  }

  toggleTable = () => {
    this.setState({ isVisible: !this.state.isVisible });
  }

  removeOrAddRow = (addRow = false) => () => {
    const { tableData } = this.state;
    if (addRow) {
      tableData.shift();
      this.setState({
        tableData,
      });
    } else {
      tableData.unshift([
        'Element added',
        false,
        60,
        'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
      ]);
      this.setState({
        tableData,
      });
    }
  }

  renderButtons() {
    const { isVisible } = this.state;
    const buttons = [
      new ButtonModel('moveRow', this.moveTableElement, 'Move row'),
      new ButtonModel('showHideTableButton', this.toggleTable, `${isVisible ? 'Hide' : 'Show'} table`),
      new ButtonModel('changeTextsButton', this.changeTexts(true), 'Change all texts'),
      new ButtonModel('changePartiallyTextsButton', this.changeTexts(), 'Change partially text'),
      new ButtonModel('removeRow', this.removeOrAddRow(true), 'Remove row'),
      new ButtonModel('addRow', this.removeOrAddRow(), 'Add row'),
    ];

    return buttons.map(({ key, event, text}) => (
      <button
        key={key}
        onClick={event}
      >
        {text}
      </button>
    ));
  }

  render() {
    const { isVisible, tableData } = this.state;
    return (
      tableData[0].length ? [
        this.renderButtons(),
        <div key="tableWithData" className="table-wrapper">
          {isVisible &&
            <table>
              <tbody>
                {this.getRows(tableData)}
              </tbody>
            </table>
          }
        </div>,
      ]
      :
      <p>loading...</p>
    );
  }
}

Table.defaultProps = {
  isBigTable: false,
};

Table.propTypes = {
  isBigTable: PropTypes.bool,
};

export default Table;
