// react-app/src/Table/Table.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import ButtonModel from "./ButtonModel";
import './Table.css';

class Table extends Component {
  state = {
    isVisible: true,
    tableData: [[]],
  };

  componentDidMount() {
    if (this.props.isBigTable) {
      const tableData = [];
      for (let i = 0; i < 300; i++) { // 30000 is fine
        if (i === 0) {
          tableData.push([
            'This is first item',
            false,
            1,
            'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
          ]);
        } else {
          tableData.push([
            'title',
            false,
            54,
            'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
          ]);
        }
      }
      this.setState({
        tableData,
      });
    } else {
      fetch('http://localhost:3001/table')
        .then(data => data.json())
        .then(({ tableData }) => {
          this.setState({
            tableData,
          });
        });
    }
  }

  selectRow = (rowIndex, cellIndex) => () => {
    const { tableData } = this.state;
    tableData[rowIndex][cellIndex] = !tableData[rowIndex][cellIndex];
    this.setState({
      tableData,
    });
  }

  getCells(cells, rowIndex) {
    return cells.map((cell, index) => {
      if (typeof cell === 'boolean') {
        return <td key={`${index}cell`}>
          <input type="checkbox" onChange={this.selectRow(rowIndex, index)} checked={cell} />
        </td>;
      } else if (typeof cell === 'string' && cell.includes('.png')) {
        return <td key={`${index}cell`}><img src={cell} alt="js logo" /></td>;
      }
      return <td key={`${index}cell`}>{cell}</td>;
    });
  }

  getRows(rows) {
    return rows.map((row, index) =>
      <tr key={`${index}row`}>
        {this.getCells(row, index)}
      </tr>
    );
  }

  moveTableElement = () => {
    const { tableData } = this.state;
    const firstRow = tableData.shift();
    tableData.splice(1, 0, firstRow);
    this.setState({
      tableData,
    });
  }

  changeTexts = (changeAll = false) => () => {
    const { tableData } = this.state;
    if (changeAll) {
      tableData.forEach(row => {
        row[0] = String(Math.random());
      });
    } else {
      for (let i = 0; i < tableData.length - 1; i += 10) {
        tableData[i][0] = String(Math.random());
      }
    }

    this.setState({
      tableData,
    });
  }

  toggleTable = () => {
    this.setState({ isVisible: !this.state.isVisible });
  }

  removeOrAddRow = (addRow = false) => () => {
    const { tableData } = this.state;
    if (addRow) {
      tableData.shift();
      this.setState({
        tableData,
      });
    } else {
      tableData.unshift([
        'Element added',
        false,
        60,
        'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
      ]);
      this.setState({
        tableData,
      });
    }
  }

  renderButtons() {
    const { isVisible } = this.state;
    const buttons = [
      new ButtonModel('moveRow', this.moveTableElement, 'Move row'),
      new ButtonModel('showHideTableButton', this.toggleTable, `${isVisible ? 'Hide' : 'Show'} table`),
      new ButtonModel('changeTextsButton', this.changeTexts(true), 'Change all texts'),
      new ButtonModel('changePartiallyTextsButton', this.changeTexts(), 'Change partially text'),
      new ButtonModel('removeRow', this.removeOrAddRow(true), 'Remove row'),
      new ButtonModel('addRow', this.removeOrAddRow(), 'Add row'),
    ];

    return buttons.map(({ key, event, text}) => (
      <button
        key={key}
        onClick={event}
      >
        {text}
      </button>
    ));
  }

  render() {
    const { isVisible, tableData } = this.state;
    return (
      tableData[0].length ? [
        this.renderButtons(),
        <div key="tableWithData" className="table-wrapper">
          {isVisible &&
            <table>
              <tbody>
                {this.getRows(tableData)}
              </tbody>
            </table>
          }
        </div>,
      ]
      :
      <p>loading...</p>
    );
  }
}

Table.defaultProps = {
  isBigTable: false,
};

Table.propTypes = {
  isBigTable: PropTypes.bool,
};

export default Table;

// angular-app/src/app/table/table.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { TableService } from './table.service';
import Row from './row.model';
import TableData from './table-data';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss'],
})
export default class TableComponent implements OnInit {
   tableData: Row[];
  private isVisible: boolean = true;

  constructor(private tableService: TableService, private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.route.data
      .subscribe(({ bigTable }: { bigTable: boolean }) => {
        if (bigTable) {
          this.tableData = this.tableService.getBigTable();
        } else {
          this.tableService.getRows().subscribe((rows: TableData) => {
            this.tableData = rows.tableData;
          });
        }
      });
  }

  moveTableElement(): void {
    const { tableData }: TableComponent = this;
    const firstRow = tableData.shift();
    tableData.splice(1, 0, firstRow);
    this.tableData = tableData;
  }

  toggleTable(): void {
    this.isVisible = !this.isVisible;
  }

  changeTexts(changeAll: boolean = false): void {
    const { tableData }: TableComponent = this;
    if (changeAll) {
      tableData.forEach(row => {
        row[0] = String(Math.random());
      });
    } else {
      for (let i = 0; i < tableData.length - 1; i += 10) {
        tableData[i][0] = String(Math.random());
      }
    }
    this.tableData = tableData;
  }

  removeOrAddRow(addRow: boolean = false): void {
    const { tableData }: TableComponent = this;
    if (addRow) {
      tableData.shift();
      this.tableData = tableData;
    } else {
      tableData.unshift([
        'Element added',
        false,
        60,
        'https://referralrock.com/wp-content/uploads/2018/08/javascript-logo_small.png',
      ]);
      this.tableData = tableData;
    }
}

  isString(element: any) {
    return typeof element === 'string';
  }
}

<button (click)="moveTableElement()">Move row</button>
<button (click)="toggleTable()">{{ isVisible ? 'Hide' : 'Show' }} table</button>
<button (click)="toggleTable()">{{ isVisible ? 'Hide' : 'Show' }} table</button>
<button (click)="changeTexts(true)">Change all texts</button>
<button (click)="changeTexts()">Change partially text</button>
<button (click)="removeOrAddRow(true)">Remove row text</button>
<button (click)="removeOrAddRow()">Add row</button>
<div *ngIf="tableData" class="table-wrapper">
  <table *ngIf="isVisible">
    <tbody>
      <tr *ngFor="let row of tableData; let rowIndex = index">
        <td *ngFor="let cell of row; let cellIndex = index">
          <div *ngIf="cell === true || cell === false">
            <input type="checkbox" [(ngModel)]="tableData[rowIndex][cellIndex]" />
          </div>
          <div *ngIf="isString(cell) && cell.includes('.png')">
            <img [src]="cell" alt="js logo">
          </div>
          <div *ngIf="!(isString(cell) && cell.includes('.png')) && !(cell === true || cell === false)">
            {{cell}}
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<p *ngIf="!tableData">loading...</p>
